theme: minima
title: "Програмування мовою C# — Методичний посібник (Частина 1)"
description: "Повний конспект лекцій і лабораторних робіт"
markdown: GFM
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
